version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.1-apache
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version  
      - run:
          name: Install project dependencies
          command: php composer.phar install 
      - run: 
          name: mv composer.phar /usr/local/bin/composer
          command: mv composer.phar /usr/local/bin/composer
      - run:
          name: composer install
          command: composer install
      - run:
          name: composer require --dev phpunit/phpunit ^7
          command: composer require --dev phpunit/phpunit ^7
      - run: 
          name: vendor/bin/phpunit --version
          command: vendor/bin/phpunit --version
      - run:
          name: Run Unit tests
          command: ./vendor/bin/phpunit test
      - setup_remote_docker:
          version: 19.03.1-ce
      - run:
          name: Build container 
          command: 
            docker build -t "1" .
      